// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteBag.Data;

#nullable disable

namespace NoteBag.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220908082032_Dates")]
    partial class Dates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NoteBag.Data.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Lorem Lorem Lorem Lorem Lorem",
                            CreatedTime = new DateTimeOffset(new DateTime(2022, 9, 8, 11, 20, 32, 716, DateTimeKind.Unspecified).AddTicks(5767), new TimeSpan(0, 3, 0, 0, 0)),
                            ModifiedTime = new DateTimeOffset(new DateTime(2022, 9, 8, 11, 20, 32, 716, DateTimeKind.Unspecified).AddTicks(5790), new TimeSpan(0, 3, 0, 0, 0)),
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Lorem Lorem Lorem Lorem Lorem",
                            CreatedTime = new DateTimeOffset(new DateTime(2022, 9, 8, 11, 20, 32, 716, DateTimeKind.Unspecified).AddTicks(5794), new TimeSpan(0, 3, 0, 0, 0)),
                            ModifiedTime = new DateTimeOffset(new DateTime(2022, 9, 8, 11, 20, 32, 716, DateTimeKind.Unspecified).AddTicks(5795), new TimeSpan(0, 3, 0, 0, 0)),
                            Title = "Dolor Sit"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Lorem Lorem Lorem Lorem Lorem",
                            CreatedTime = new DateTimeOffset(new DateTime(2022, 9, 8, 11, 20, 32, 716, DateTimeKind.Unspecified).AddTicks(5797), new TimeSpan(0, 3, 0, 0, 0)),
                            ModifiedTime = new DateTimeOffset(new DateTime(2022, 9, 8, 11, 20, 32, 716, DateTimeKind.Unspecified).AddTicks(5798), new TimeSpan(0, 3, 0, 0, 0)),
                            Title = "Amet "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
